export const AUTH_LOGIN ="AUTH_LOGIN" 
export const AUTH_LOGIN_SUCCESS ="AUTH_LOGIN_SUCCESS"
export const AUTH_LOGIN_FAILURE ="AUTH_LOGIN_FAILURE"

export const QUESTION_ADD = "QUESTION_ADD"
export const QUESTION_DELETE = "QUESTION_DELETE"
export const QUESTION_UPDATE = "QUESTION_UPDATE"

export const QUESTION_GETALL = "QUESTION_GETALL"
export const QUESTION_GETALL_SUCCESS = "QUESTION_GETALL_SUCCESS"
export const QUESTION_GETALL_FAILURE = "QUESTION_GETALL_FAILURE"
